services:
    caddy:
        build:
            target: caddy-dev
        volumes:
            - ../config/docker/Caddyfile:/etc/caddy/Caddyfile:ro
            - ../public/:/srv/public:ro

    php:
        build:
            target: php-dev
        volumes:
            - ../config/docker/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-app.conf:ro
            - ../config/docker/php.ini:/usr/local/etc/php/conf.d/zz-app.ini:ro

    db:
        build:
            target: mariadb-dev
        volumes:
            - ../config/docker/mariadb.cnf:/etc/mysql/mariadb.conf.d/80-app.cnf:ro
